services:
  # FastAPI Application

  # Nginx Service -> Like uvicorn

  # PostgreSQL (pgvector)
  pgvector:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector
    ports:
      - "5432:5432"
    volumes:
      - 'pgvector:/var/lib/postgresql/data'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  # Qdrant (vectorDB)

  # Prometheus Monitoring 

  # Grafana Dashboard


  # Node Exporter for system metrics

  # PostgreSQL Exporter for postgres metrics

