services:
  # FastAPI Application

  # Nginx Service -> Like uvicorn

  # PostgreSQL (pgvector)
  pgvector:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector
    ports:
      - "5432:5432"
    volumes:
      - 'pgvector:/var/lib/postgresql/data'
    env_file:
      - ./env/.env.postgres
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["executable", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s


  # Qdrant (vectorDB)

  # Prometheus Monitoring 

  # Grafana Dashboard


  # Node Exporter for system metrics

  # PostgreSQL Exporter for postgres metrics

