FROM ghcr.io/astral-sh/uv:0.6.14-python3.10-bookworm

WORKDIR /app

# Install additional system dependencies for lxml and other packages
RUN apt-get update && apt-get install -y \
    build-essential \
    libavif-dev pkg-config \
    libjpeg-dev \
    gcc unzip zip \
    python3-dev \
    libxml2-dev \
    libffi-dev \
    libgl1-mesa-glx \
    curl \
    && rm -rf /var/lib/apt/lists/*


COPY src/requirements.txt .

RUN uv pip install -r requirements.txt --system

# Take all the src file
COPY src/ . 

# Create directory structure for Alembic
RUN mkdir -p /app/models/db_schemes/rag/

COPY docker/minirag/alembic.ini /app/models/db_schemes/rag/alembic.ini

COPY docker/minirag/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]

